version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: ./react-frontend
    ports:
      - "3000:80"
